### ISSUE TITLE
Remove minimum-stability:dev in composer.json and use stabilty flags

### ISSUE THREAD

**Issue by alch** [elcodi/bamboo-store#60]
We are using [`minimum-stability: dev`](https://getcomposer.org/doc/04-schema.md#minimum-stability) in our composer.json, which is great for development environments but can be problematic since it lowers the `dev` stability for all the dependent packages: until we follow a more strict semanting versioning scheme I propose to use the `@dev` stability flag when requiring `elcodi/elcodi` from web applications and remove the `minimum-stability` field.

**Comment by jromero86** [comment]
Hello,

paymentsuite/free-payment-bundle need "dev-master" flag
